version: "3.8"

services:
  # Permissions service
  gleam_auth:
    build: .
    ports:
      - "8000:8000"
    environment:
      # will update later
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: admin
      DB_PASSWORD: password
      SECRET_KEY: temp_secret
    volumes:
      - ./:/app
    depends_on:
      - mongodb  # Ensure Postgres is started before Gleam

  # Mongo database
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: quasimoto
    volumes:
      - mongodb:/data/db  # Persistant storage for Mongo data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # Sets up auth

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
networks:
  backend:
    external: true

volumes:
  # Persistent storage volume for Mongo data
  mongodb: